### ISSUE TITLE
Length token filter should be removed from mapping

### ISSUE THREAD

**Issue by duzvik** [Cyb3rWard0g/HELK#132] opened 2018-12-13 15:16 UTC
**Describe the problem**
Length token filters **two_or_more_tokenizer_limit_filter** and **three_or_more_tokenizer_limit_filter** 
 should be removed  from /docker/helk-logstash/output_templates/50-logs-winevent-all.json

Because you are working with SIGMa integration and there are many conditions with length 2 and 3 in sigma rules. For example, check https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_susp_procdump.yml

```
 ProcessCommandLine:
            - "* -ma *"
```

And current mapping with length token filters just drops this condition.

**Comment by neu5ron** [comment] 2018-12-13 16:52
thanks for the suggestion, I am definitely open to changing this mapping. However, before I would do so - do you have an example of it droping this condition? also, this would be converted to ProcessCommandLine.keyword , thus ignoring the tokenization of the CLI field.
also, I have found this analyzer to be much better for command line and file names. because the default analyzer is built for things similar to a "book", example containing words with spaces between each word.
Example:
EmployeePayroll.docx
with the custom analyzer you could search "employee" or you could also search "payroll". However, with the default analyzer, you would have to search "employeepayroll" to find that.

**Comment by duzvik** [comment] 2018-12-13 17:23
Here is an example, what I mean:

```
PUT example-index-with-analyzer
{
	"settings": {
		"analysis": {
			"analyzer": {
				"cli_n_file_analyzer": {
					"type": "custom",
					"filter": ["case_change_only_delim_filter", "three_or_more_tokenizer_limit_filter", "cli_n_file_word_delim_filter", "two_or_more_tokenizer_limit_filter", "lowercase", "unique"],
					"tokenizer": "standard"
				}
			},
			"filter": {
				"cli_n_file_word_delim_filter": {
					"type": "word_delimiter",
					"generate_word_parts": true,
					"split_on_case_change": true,
					"split_on_numerics": false,
					"stem_english_possessive": false,
					"generate_number_parts": true,
					"preserve_original": true
				},
				"case_change_only_delim_filter": {
					"type": "word_delimiter",
					"generate_word_parts": true,
					"split_on_case_change": true,
					"split_on_numerics": false,
					"stem_english_possessive": false,
					"generate_number_parts": false,
					"preserve_original": true
				},
				"two_or_more_tokenizer_limit_filter": {
					"type": "length",
					"min": 2
				},
				"three_or_more_tokenizer_limit_filter": {
					"type": "length",
					"min": 3
				}
			}
		}
	},
	"mappings": {
		"doc": {
			"properties": {
				"process_command_line": {
					"type": "text",
					"norms": false,
					"analyzer": "cli_n_file_analyzer",
					"fields": {
						"keyword": {
							"ignore_above": 7500,
							"type": "keyword"
						}
					}
				}
			}
		}
	}
}

PUT example-index-with-analyzer/doc/1
{
  "process_command_line": "C\\:\\Windows\\system32\\lsass.exe",
  "event_id": 1
}

GET example-index-with-analyzer/doc/1

#example of query from sigma's win_susp_procdump.yml
#result unexpected
GET example-index-with-analyzer/_search?pretty
{
  "query": {
    "query_string": {
      "query":"(event_id:\"1\" AND process_command_line:(\"* -ma *\") AND process_command_line:(\"* lsass.exe*\"))"
      }
  }
}

#lets remove two_or_more_tokenizer_limit_filter and  three_or_more_tokenizer_limit_filter  from mapping

POST example-index-with-analyzer/_close
PUT example-index-with-analyzer/_settings
{
  "analysis" : {
    "analyzer":{
        "cli_n_file_analyzer": {
          "type": "custom",
          "filter": [ "case_change_only_delim_filter",  "cli_n_file_word_delim_filter", "lowercase", "unique" ],
          "tokenizer": "standard"
        }
      }
    }
}
POST example-index-with-analyzer/_open

#repeat search, result expected
GET example-index-with-analyzer/_search?pretty
{
  "query": {
    "query_string": {
      "query":"(event_id:\"1\" AND process_command_line:(\"* -ma *\") AND process_command_line:(\"* lsass.exe*\"))"
      }
  }
}
#cleanup
DELETE example-index-with-analyzer
```

> Example:
EmployeePayroll.docx
with the custom analyzer, you could search "employee" or you could also search "payroll". However, with the default analyzer, you would have to search "employeepayroll" to find that.

Tokenizer that responsible for this(case_change_only_delim_filter) -  we don't touch.

**Comment by neu5ron** [comment] 2018-12-13 17:30
its the compatibilty with all the other databases that SIGMA has to use the appended and prepended "*"
otherwise we could just write the rule as "lsass"

**Comment by neu5ron** [comment] 2018-12-13 17:34
one more note, for the background of 2 and 3 or more. is that since we are using case change, we would not want to create tokens for something such as:
ThIsIsGoInGtOcReAtEaLoToFToKeNs

Which would create 31 tokens, and not sure that would make sense for people to search for "a" and get many results

**Comment by duzvik** [comment] 2018-12-13 18:06
> Can you try your example using process_command_line.keyword?
Same results.

> That should be the default for SIGMA anyways, is to use a .keyword, is that correct @Cyb3rWard0g ?
Last changes to Sigma(4 days ago https://github.com/Neo23x0/sigma/commit/2091c90538e83b2563e9bba3f2246bf8cbeedc6c ) fix .keyword but it's related to query_key and aggregations.

**Comment by neu5ron** [comment] 2018-12-13 19:15
am I missing something? running your exact example I get expected results..
see screenshots below:

![selection_001](https://user-images.githubusercontent.com/6351842/49961762-7216e580-fee1-11e8-9880-ef5e314bd7cf.png)

![selection_002](https://user-images.githubusercontent.com/6351842/49961794-865ae280-fee1-11e8-9af9-a6ac7fc31382.png)

![selection_003](https://user-images.githubusercontent.com/6351842/49961798-88bd3c80-fee1-11e8-9d0d-db41bc8e5a0c.png)

**Comment by duzvik** [comment] 2018-12-14 06:31
Expected result is empty response.
`"query":"(event_id:\"1\" AND process_command_line:(\"* -ma *\") AND process_command_line:(\"* lsass.exe*\"))"
`
Threre is no any "-ma" part  in process_command_line.

**Comment by neu5ron** [comment] 2018-12-14 15:00
ah yes, you are correct. So this is very interesting. After taking some time to dig into this, I have noticed that something else is going on.
If a search token results in null tokens it matches almost everything when using query string (I have only tested this at the moment).
empty tokens should not match anything, unless this is a bug or there is some setting in the query string parameter that causes this...? I am going to dig into this through out the day. but I think this boils down to it creating a "null" token and so it then skips right over it.

I changed them to .keyword and got the expected result. Can you please try the following:
`GET example-index-with-analyzer/_search
{
  "query": {
    "query_string": {
      "query":"event_id:\"1\" AND process_command_line.keyword:\"* -ma *\" AND process_command_line.keyword:\"* lsass.exe*\""
      }
  }
}`


![selection_00](https://user-images.githubusercontent.com/6351842/50009923-2f5b1900-ff86-11e8-997d-a73149bb5958.png)
![selection_001](https://user-images.githubusercontent.com/6351842/50009929-3124dc80-ff86-11e8-9eb3-48b149153d94.png)
![selection_002](https://user-images.githubusercontent.com/6351842/50009934-32560980-ff86-11e8-9573-f34867721c46.png)
![selection_003](https://user-images.githubusercontent.com/6351842/50009940-3550fa00-ff86-11e8-9b08-a0a2c5953e45.png)
![selection_004](https://user-images.githubusercontent.com/6351842/50009952-3bdf7180-ff86-11e8-8a29-e534e4455694.png)



I also have something else I am thinking can help/solve these things no matter the analyzer

**Comment by neu5ron** [comment] 2018-12-14 16:06
correct, which they are fixing in sigmac to use .keyword. Going to close this issue, as this is expected and not a bug as you mentioned. and also as you mentioned analyzer is applied at write and during search and the analyzer results in no token. Also, I have explained a few other reasons further below why I think we should keep the current analyzer.

Here is a good example of why to do char limit, in this example someone would be able to evade "exe" search by just camel casing "ExE":
#### Current HELK Analyzer
[current-helk-analyzer](https://user-images.githubusercontent.com/6351842/50013827-40108c80-ff90-11e8-81d8-932634c099b6.png)
#### Recommended HELK Analyzer
[recommended-helk-analyzer](https://user-images.githubusercontent.com/6351842/50013831-41da5000-ff90-11e8-9258-2b60e2165bca.png)



The reason for the char limits were to reduce the tokens while still providing better functionality than the standard analyzer. I am not sure how much functionality it would add to search for only single or double characters.. tokenizing "c" and other single character parameters does not seem to be the most efficient scenario, for example in "C:\\Users\\Nate\\analyze.txt".


If sigmac does not change to use  .keyword there will always be different bugs for certain scenarios. For example, if someone were to only want "-MA" and there was CLI with "-ma" the "-MA" would match unless using .keyword. because the analyzer would convert "-MA" to "-ma".
This same example above can apply to all sorts of fields with case variants and other things.

In the future I may add search_quote_analyzer parameter, so either way - I am glad you brought this issue to my attention.

**Closed** 2018-12-14 16:09 UTC
